name: odiyo
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+20

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.5

  #Firebase
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  firebase_dynamic_links: ^5.3.4
  firebase_storage: ^11.2.5
  paginate_firestore:
    git:
      url: https://github.com/waqadArshad/paginate_firestore.git
  cloud_functions: ^4.3.4
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4

  #Auth
  google_sign_in: 5.4.2
  sign_in_with_apple: 4.1.0
  crypto: 3.0.2
  flutter_facebook_auth: 4.4.1+1
  twitter_login: 4.2.3

  #Utilities
  nanoid: 1.0.0
  delayed_display: 2.0.0
  font_awesome_flutter: 10.2.1
  cached_network_image: 3.2.2
  uuid: 3.0.6
  timeago: 3.3.0
  url_launcher: 6.1.6
  intl: 0.17.0
  flutter_launcher_icons: 0.10.0
  #store_launcher: 1.0.1
  #share: 2.0.4
  shared_preferences: 2.0.15
  flutter_rating_bar: 4.0.1
  smooth_page_indicator: 1.0.0+2
  image_cropper: 3.0.0
  image_picker: 0.8.6
  flutter_native_image: 0.0.6+1
  carousel_slider: 4.1.1
  loading_animation_widget: 1.2.0+3
  algolia: 1.1.1
  flutter_stripe: 3.3.0
  miniplayer: 1.0.1
  hive: 2.2.3
  assets_audio_player: 3.0.6
  just_audio: 0.9.31
  audio_session: 0.1.11
  rxdart: '>=0.26.0 <0.28.0'
  geolocator: 9.0.2
  #geocoder: 0.2.1
  flutter_credit_card: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/dummy/

  fonts:
    - family: Font2
      fonts:
        - asset: assets/fonts/nunitofont.ttf
